version: '3.8'
services:
  hugo:
      image: klakegg/hugo
      container_name: myblog_hugo
      build:
        context: .
        dockerfile: ./Dockerfile/blogBuild.Dockerfile
      command: server
      volumes:
        - ".:/misarb/src"
      ports:
         - "1313:1313"
     




