version: '3'
services:
  hugo:
      image: klakegg/hugo
      container_name: myblog_hugo
      build:
        dockerfile: ./Dockerfile/.Dockerfile
      command: server
      volumes:
        - ".:/src"
      ports:
         - "1313:1313"
     




